/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/choose-role`; params?: Router.UnknownInputParams; } | { pathname: `/contractor-homepage`; params?: Router.UnknownInputParams; } | { pathname: `/contractor-signin`; params?: Router.UnknownInputParams; } | { pathname: `/contractor-signup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/worker-homepage`; params?: Router.UnknownInputParams; } | { pathname: `/worker-signin`; params?: Router.UnknownInputParams; } | { pathname: `/worker-signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/choose-role`; params?: Router.UnknownOutputParams; } | { pathname: `/contractor-homepage`; params?: Router.UnknownOutputParams; } | { pathname: `/contractor-signin`; params?: Router.UnknownOutputParams; } | { pathname: `/contractor-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/worker-homepage`; params?: Router.UnknownOutputParams; } | { pathname: `/worker-signin`; params?: Router.UnknownOutputParams; } | { pathname: `/worker-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/choose-role${`?${string}` | `#${string}` | ''}` | `/contractor-homepage${`?${string}` | `#${string}` | ''}` | `/contractor-signin${`?${string}` | `#${string}` | ''}` | `/contractor-signup${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/worker-homepage${`?${string}` | `#${string}` | ''}` | `/worker-signin${`?${string}` | `#${string}` | ''}` | `/worker-signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/choose-role`; params?: Router.UnknownInputParams; } | { pathname: `/contractor-homepage`; params?: Router.UnknownInputParams; } | { pathname: `/contractor-signin`; params?: Router.UnknownInputParams; } | { pathname: `/contractor-signup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/worker-homepage`; params?: Router.UnknownInputParams; } | { pathname: `/worker-signin`; params?: Router.UnknownInputParams; } | { pathname: `/worker-signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
